services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: backend
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - maven-repository:/root/.m2
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: 'postgres:16-alpine'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=pos_db'
      - 'POSTGRES_PASSWORD=phaiecobyte'
      - 'POSTGRES_USER=phaiecobyte'
    ports:
      - '5433:5432'
    volumes:
      - pos_data:/var/lib/postgresql/data

volumes:
  maven-repository:
  pos_data: