spring.application.name=pos-system
server.port=8082

#Telegram bot
telegram.bot.token=8269397469:AAGpecrkI-xmsvqzVfkR8NpyHqTmSn9XRdo
telegram.bot.chat-id=1120555808

#Database Configuration for Development
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/phai?currentSchema=pos_system
spring.datasource.username=phai
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# --- SpringDoc OpenAPI & OAuth2 Configuration ---
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# This client-id must exist in your Keycloak realm
springdoc.swagger-ui.oauth.client-id=my-spring-boot-client
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true

# --- Spring Security OAuth2 Resource Server Configuration ---
# This URI is used by your Spring Boot app to validate incoming JWTs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8083/realms/my-spring-boot-realm