spring.application.name=backend

#=================== hibernate ====================
spring.jpa.hibernate.ddl-auto=update

#=================== Security ======================
app.jwt-key = 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt-expiration-ms=900000
app.jwt-refresh-expiration-ms=604800000