/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiResponseVoid { 
    timestamp?: string;
    status?: number;
    success?: boolean;
    message?: string;
    data?: any | null;
}

