/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageProductRes } from './pageProductRes';


export interface ApiResponsePageProductRes { 
    timestamp?: string;
    status?: number;
    success?: boolean;
    message?: string;
    data?: PageProductRes;
}

