/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryRes } from './categoryRes';


export interface ApiResponseCategoryRes { 
    timestamp?: string;
    status?: number;
    success?: boolean;
    message?: string;
    data?: CategoryRes;
}

