/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateReq { 
    tenantIdentifier: string;
    businessName: string;
    contactPhone?: string;
    subscriptionEndDate?: string;
}

