/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductReq { 
    code: string;
    name: string;
    description?: string;
    price: number;
    stockable?: boolean;
    categoryId: string;
    imageUrl?: string;
}

