/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductRes { 
    id?: string;
    code?: string;
    name?: string;
    description?: string;
    price?: number;
    stockable?: boolean;
    currentStock?: number;
    active?: boolean;
    imageUrl?: string;
    categoryId?: string;
    categoryName?: string;
    createdAt?: string;
}

