/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterReq { 
    fullName?: string;
    username?: string;
    password?: string;
    email?: string;
    roleName?: string;
}

