/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StockReq { 
    productId: string;
    type: StockReq.TypeEnum;
    quantity: number;
    remark?: string;
}
export namespace StockReq {
    export const TypeEnum = {
        In: 'IN',
        Out: 'OUT',
        Sale: 'SALE',
        Adjustment: 'ADJUSTMENT'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


