export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './categoryController.service';
import { CategoryControllerService } from './categoryController.service';
export * from './productController.service';
import { ProductControllerService } from './productController.service';
export * from './roleController.service';
import { RoleControllerService } from './roleController.service';
export * from './stockController.service';
import { StockControllerService } from './stockController.service';
export * from './tenantController.service';
import { TenantControllerService } from './tenantController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AuthControllerService, CategoryControllerService, ProductControllerService, RoleControllerService, StockControllerService, TenantControllerService, UserControllerService];
